ShopTARgv23/Models/ChuckNorris/ChuckNorrisJokesViewModel.cs
namespace ShopTARgv23.Models.ChuckNorris
{
    public class ChuckNorrisJokesViewModel
    {
        public string IconUrl { get; set; }
        public string Id { get; set; }
        public string Url { get; set; }
        public string Value { get; set; }
    }
}

ShopTARgv23/Models/ChuckNorris/JokeViewModel.cs
namespace ShopTARgv23.Models.ChuckNorris
{
    public class JokeViewModel
    {
        public string[] Categories { get; set; }
        public DateTime CreatedAt { get; set; }
        public string IconUrl { get; set; }
        public string Id { get; set; }
        public DateTime UpdatedAt { get; set; }
        public string Url { get; set; }
        public string Value { get; set; }
    }
}

ShopTARgv23/Controllers/ChuckNorrisController.cs
using Microsoft.AspNetCore.Mvc;
using ShopTARgv23.Core.Dto.ChuckNorris;
using ShopTARgv23.Core.ServiceInterface;
using ShopTARgv23.Models.ChuckNorris;

namespace ShopTARgv23.Controllers
{
    public class ChuckNorrisController : Controller
    {
        private readonly IChuckNorrisServices _services;
        public ChuckNorrisController (IChuckNorrisServices services)
        {
            _services = services;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> GetRandomJokeByCategory(string category)
        {
            var joke = await _services.GetJokeByCategoryAsync(category);

            var model = new JokeViewModel
            {
                Categories = joke.Categories,
                CreatedAt = joke.CreatedAt,
                IconUrl = joke.IconUrl,
                Id = joke.Id,
                UpdatedAt = joke.UpdatedAt,
                Url = joke.Url,
                Value = joke.Value
            };

            return View("Joke", model);
        }
    }
}

ShopTARgv23/Views/ChuckNorris/Index.cshtml
@model ShopTARgv23.Models.ChuckNorris.ChuckNorrisJokesViewModel

<div class="container">
    <div class="h1">Chuck Norris Jokes</div>
    <div class="h4">
        Choose a category to see a random joke
    </div>

    <form method="post">
        <label for="category">Select a category:</label>
        <select name="category">
            <option value="animal">Animal</option>
            <option value="career">Career</option>
            <option value="celebrity">Celebrity</option>
            <option value="dev">Dev</option>
            <option value="explicit">Explicit</option>
            <option value="fashion">Fashion</option>
            <option value="food">Food</option>
            <option value="history">History</option>
            <option value="money">Money</option>
            <option value="movie">Movie</option>
            <option value="music">Music</option>
            <option value="political">Political</option>
            <option value="religion">Religion</option>
            <option value="science">Science</option>
            <option value="sport">Sport</option>
            <option value="travel">Travel</option>
        </select>
        <button asp-controller="ChuckNorris" asp-action="GetRandomJokeByCategory">Get Joke</button>
    </form>
</div>

ShopTARgv23/Views/ChuckNorris/Joke.cshtml
@model ShopTARgv23.Models.ChuckNorris.JokeViewModel

<div class="container">
    <div class="h1">Chuck Norris Joke Details</div>
    <hr />

    <dl>
        <div>
            <label asp-for="Id" class="col-sm-2"></label>
            @Html.DisplayFor(model => model.Id)
        </div>

        <div>
            <label asp-for="Categories" class="col-sm-2"></label>
            @Html.DisplayFor(model => model.Categories)
        </div>

        <div>
            <label asp-for="Url" class="col-sm-2"></label>
            <a href="@Html.DisplayFor(model => model.Url)">@Html.DisplayFor(model => model.Url)</a>
        </div>

        <div>
            <label asp-for="Value" class="col-sm-2"></label>
            @Html.DisplayFor(model => model.Value)
        </div>
    </dl>

    <a asp-action="Index" asp-controller="ChuckNorris">Back</a>
</div>