ShopTARgv23/Models/RealEstate/RealEstateCreateUpdateViewModel.cs
namespace ShopTARgv23.Models.RealEstate
{
    public class RealEstateCreateUpdateViewModel
    {
        public Guid? Id { get; set; }
        public string? Location { get; set; }
        public double? Size { get; set; }
        public int? RoomNumber { get; set; }
        public string? BuildingType { get; set; }

        public List<IFormFile> Files { get; set; }
        public List<RealEstateImageViewModel> Image { get; set; }
            = new List<RealEstateImageViewModel>();
        public DateTime? CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }
    }
}

ShopTARgv23/Models/RealEstate/RealEstateDeleteViewModel.cs
namespace ShopTARgv23.Models.RealEstate
{
    public class RealEstateDeleteViewModel
    {
        public Guid? Id { get; set; }
        public string? Location { get; set; }
        public double? Size { get; set; }
        public int? RoomNumber { get; set; }
        public string? BuildingType { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }
        public List<RealEstateImageViewModel> Image { get; set; }
            = new List<RealEstateImageViewModel>();
    }
}

ShopTARgv23/Models/RealEstate/RealEstateDetailsViewModel.cs
namespace ShopTARgv23.Models.RealEstate
{
    public class RealEstateDetailsViewModel
    {
        public Guid? Id { get; set; }
        public string? Location { get; set; }
        public double? Size { get; set; }
        public int? RoomNumber { get; set; }
        public string? BuildingType { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }
        public List<RealEstateImageViewModel> Image { get; set; }
            = new List<RealEstateImageViewModel>();
}
}

ShopTARgv23/Models/RealEstate/RealEstateImageViewModel.cs
namespace ShopTARgv23.Models.RealEstate
{
    public class RealEstateImageViewModel
    {
        public Guid ImageId { get; set; }
        public string? ImageTitle { get; set; }
        public byte[]? ImageData { get; set; }
        public string? Image {  get; set; }
        public Guid? RealEstateId { get; set; }

    }
}

ShopTARgv23/Models/RealEstate/RealEstateIndexViewModel.cs
namespace ShopTARgv23.Models.RealEstate
{
    public class RealEstateIndexViewModel
    {
        public Guid? Id { get; set; }
        public string? Location { get; set; }
        public double? Size { get; set; }
        public int? RoomNumber { get; set; }
        public string? BuildingType { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }
    }
}

ShopTARgv23/Controllers/RealEstateController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShopTARgv23.Core.Dto;
using ShopTARgv23.Core.ServiceInterface;
using ShopTARgv23.Data;
using ShopTARgv23.Models.RealEstate;

namespace ShopTARgv23.Controllers
{
    public class RealEstateController : Controller
    {
        private readonly ShopTARgv23Context _context;
        private readonly IRealEstate _realEstate;
        private readonly IFileServices _fileServices;
        public RealEstateController(ShopTARgv23Context context, IRealEstate realEstate, IFileServices fileServices)
        {
            _context = context;
            _realEstate = realEstate;
            _fileServices = fileServices;
        }
        public IActionResult Index()
        {
            var result = _context.RealEstates
                .Select(x => new RealEstateIndexViewModel
                {
                    Id = x.Id,
                    Location = x.Location,
                    Size = x.Size,
                    RoomNumber = x.RoomNumber,
                    BuildingType = x.BuildingType,
                });

            return View(result);
        }

        [HttpGet]
        public IActionResult Create()
        {
            RealEstateCreateUpdateViewModel estate = new();

            return View("CreateUpdate", estate);
        }

        [HttpPost]
        public async Task<IActionResult> Create(RealEstateCreateUpdateViewModel vm)
        {
            var dto = new RealEstateDto()
            {
                Id = vm.Id,
                Location = vm.Location,
                Size = vm.Size,
                RoomNumber = vm.RoomNumber,
                BuildingType = vm.BuildingType,
                CreatedAt = vm.CreatedAt,
                ModifiedAt = vm.ModifiedAt,
                Files = vm.Files,
                Image = vm.Image
                    .Select(x => new FileToDatabaseDto
                    {
                        Id = x.ImageId,
                        ImageData = x.ImageData,
                        ImageTitle = x.ImageTitle,
                        RealEstateId = x.RealEstateId,
                    }).ToArray()
            };

            var result = await _realEstate.Create(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index), vm);
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var estate = await _realEstate.Details(id);
            if (estate == null) { return NotFound(); }

            var images = await _context.FileToDatabases
               .Where(x => x.RealEstateId == id)
               .Select(y => new RealEstateImageViewModel
               {
                   ImageId = y.Id,
                   RealEstateId = y.Id,
                   ImageData = y.ImageData,
                   ImageTitle = y.ImageTitle,
                   Image = string.Format("data:image/gif;base64,{0}", Convert.ToBase64String(y.ImageData)),
               }).ToArrayAsync();

            var vm = new RealEstateDetailsViewModel
            {
                Id = estate.Id,
                Location = estate.Location,
                Size = estate.Size,
                RoomNumber = estate.RoomNumber,
                BuildingType = estate.BuildingType,
                CreatedAt = estate.CreatedAt,
                ModifiedAt = estate.ModifiedAt
            };
            vm.Image.AddRange(images);


            return View(vm);
        }

        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            var estate = await _realEstate.Details(id);
            if (estate == null) { return NotFound(); }

            var images = await _context.FileToDatabases
               .Where(x => x.RealEstateId == id)
               .Select(y => new RealEstateImageViewModel
               {
                   ImageId = y.Id,
                   RealEstateId = y.Id,
                   ImageData = y.ImageData,
                   ImageTitle = y.ImageTitle,
                   Image = string.Format("data:image/gif;base64,{0}", Convert.ToBase64String(y.ImageData)),
               }).ToArrayAsync();

            var vm = new RealEstateCreateUpdateViewModel();

            vm.Id = estate.Id;
            vm.Location = estate.Location;
            vm.Size = estate.Size;
            vm.RoomNumber = estate.RoomNumber;
            vm.BuildingType = estate.BuildingType;
            vm.CreatedAt = estate.CreatedAt;
            vm.ModifiedAt = estate.ModifiedAt;
            vm.Image.AddRange(images);

            return View("CreateUpdate", vm);
        }

        [HttpPost]
        public async Task<IActionResult> Update(RealEstateCreateUpdateViewModel vm)
        {
            var dto = new RealEstateDto()
            {
                Id = vm.Id,
                Location = vm.Location,
                Size = vm.Size,
                RoomNumber = vm.RoomNumber,
                BuildingType = vm.BuildingType,
                ModifiedAt = DateTime.Now,
                CreatedAt = vm.CreatedAt,
                Files = vm.Files,
                Image = vm.Image.Select(x => new FileToDatabaseDto
                {
                    Id = x.ImageId,
                    ImageData = x.ImageData,
                    ImageTitle = x.ImageTitle,
                    RealEstateId = x.RealEstateId,
                }).ToArray(),
            };

            var result = await _realEstate.Update(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var estate = await _realEstate.Details(id);

            if (estate == null)
            {
                return NotFound();
            }

            var images = await _context.FileToDatabases
              .Where(x => x.RealEstateId == id)
              .Select(y => new RealEstateImageViewModel
              {
                  ImageId = y.Id,
                  RealEstateId = y.Id,
                  ImageData = y.ImageData,
                  ImageTitle = y.ImageTitle,
                  Image = string.Format("data:image/gif;base64,{0}", Convert.ToBase64String(y.ImageData))
              }).ToArrayAsync();

            var vm = new RealEstateDeleteViewModel();

            vm.Id = id;
            vm.Id = estate.Id;
            vm.Location = estate.Location;
            vm.Size = estate.Size;
            vm.RoomNumber = estate.RoomNumber;
            vm.BuildingType = estate.BuildingType;
            vm.CreatedAt = estate.CreatedAt;
            vm.ModifiedAt = estate.ModifiedAt;
            vm.Image.AddRange(images);

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmation(Guid id)
        {
            var estate = await _realEstate.Delete(id);

            if (estate == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> RemoveImage(RealEstateImageViewModel file)
        {
            var dto = new FileToDatabaseDto()
            {
                Id = file.ImageId,
            };

            var image = await _fileServices.RemoveImageFromDatabase(dto);

            if(image == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

ShopTARgv23/Views/RealEstate/CreateUpdate.cshtml
@model ShopTARgv23.Models.RealEstate.RealEstateCreateUpdateViewModel

<div class="h1">
    Real Estate
</div>

@if (Model.Id.HasValue) { <h1>Update</h1> }
else { <h3>Create</h3> }
<div>
    <hr />
    <form method="post" enctype="multipart/form-data">
        <input asp-for="Id" type="hidden" />
        <input asp-for="CreatedAt" type="hidden" />
        <input asp-for="ModifiedAt" type="hidden" />

        <div>
            <label asp-for="Location"></label>
            <div class="col-sm-10">
                <input asp-for="Location" class="form-control" />
            </div>
        </div>

        <div>
            <label asp-for="Size"></label>
            <div class="col-sm-10">
                <input asp-for="Size" class="form-control" />
            </div>
        </div>

        <div>
            <label asp-for="RoomNumber"></label>
            <div class="col-sm-10">
                <input asp-for="RoomNumber" class="form-control" />
            </div>
        </div>

        <div>
            <label asp-for="BuildingType"></label>
            <div class="col-sm-10">
                <input asp-for="BuildingType" class="form-control" />
            </div>
        </div>

        <div>
            <label asp-for="Files"></label>
            <div class="col-sm-10">
                <div class="custom-file">
                    <input asp-for="Files" class="form-control" multiple type="file"/>
                </div>
            </div>
        </div>

        <div>
            @foreach (var img in Model.Image)
            {
                <partial name="Image" model="img" />
                <input asp-action="removeImage" asp-controller="RealEstate" asp-route-imageId="@img.ImageId" type="submit" class="btn button" value="Remove Images" />
            }
        </div>

        @if (Model.Id.HasValue)
        {
            <input asp-action="update" asp-controller="RealEstate" type="submit" class="button" value="Update" />
        }
        else
        {
            <input asp-action="create" asp-controller="RealEstate" type="submit" class="button" value="Create" />
        }
    </form>

    <a asp-action="index" asp-controller="RealEstate">Back</a>
</div>

ShopTARgv23/Views/RealEstate/Delete.cshtml
@model ShopTARgv23.Models.RealEstate.RealEstateDeleteViewModel

<h1>Delete</h1>
<div class="h1">
    Real Estate
</div>
<div>
    <hr />
    <dl>
        <div>
            <label asp-for="Id" class="col-sm-2"></label>
            @Html.DisplayFor(model => model.Id)
        </div>

        <div>
            <label asp-for="Location" class="col-sm-2"></label>
            @Html.DisplayFor(model => model.Location)
        </div>

        <div>
            <label asp-for="Size" class="col-sm-2"></label>
            @Html.DisplayFor(model => model.Size)
        </div>

        <div>
            <label asp-for="RoomNumber" class="col-sm-2"></label>
            @Html.DisplayFor(model => model.RoomNumber)
        </div>

        <div>
            <label asp-for="BuildingType" class="col-sm-2"></label>
            @Html.DisplayFor(model => model.BuildingType)
        </div>

        <div>
            <label asp-for="CreatedAt" class="col-sm-2"></label>
            @Html.DisplayFor(model => model.CreatedAt)
        </div>

        <div>
            <label asp-for="ModifiedAt" class="col-sm-2"></label>
            @Html.DisplayFor(model => model.ModifiedAt)
        </div>

        @foreach (var images in Model.Image)
        {
            <partial name="Image" model="images" />
        }

        <form asp-action="DeleteConfirmation">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Delete" class="button" />
        </form>
    </dl>

    <a asp-action="Index" asp-controller="RealEstate">Back</a>
</div>

ShopTARgv23/Views/RealEstate/Details.cshtml
@model ShopTARgv23.Models.RealEstate.RealEstateDetailsViewModel

<h1>Details</h1>
<div class="h1">
    Real Estate
</div>
<div>
    <hr />
    <dl>
        <div>
            <label asp-for="Id" class="col-sm-2"></label>
            @Html.DisplayFor(model => model.Id)
        </div>

        <div>
            <label asp-for="Location" class="col-sm-2"></label>
            @Html.DisplayFor(model => model.Location)
        </div>

        <div>
            <label asp-for="Size" class="col-sm-2"></label>
            @Html.DisplayFor(model => model.Size)
        </div>

        <div>
            <label asp-for="RoomNumber" class="col-sm-2"></label>
            @Html.DisplayFor(model => model.RoomNumber)
        </div>

        <div>
            <label asp-for="BuildingType" class="col-sm-2"></label>
            @Html.DisplayFor(model => model.BuildingType)
        </div>

        <div>
            <label asp-for="CreatedAt" class="col-sm-2"></label>
            @Html.DisplayFor(model => model.CreatedAt)
        </div>

        <div>
            <label asp-for="ModifiedAt" class="col-sm-2"></label>
            @Html.DisplayFor(model => model.ModifiedAt)
        </div>
        @foreach (var images in Model.Image)
        {
            <partial name="Image" model="images" />
        }
    </dl>

    <a asp-action="Index" asp-controller="RealEstate">Back</a>
</div>

ShopTARgv23/Views/RealEstate/Image.cshtml
@model ShopTARgv23.Models.RealEstate.RealEstateImageViewModel

<div class="form-group col-sm-5">
    <div>@Model.ImageTitle</div>
    <img class="card-img-top" src="@Model.Image" asp-append-version="true" />
</div>

ShopTARgv23/Views/RealEstate/Index.cshtml
@model IEnumerable<ShopTARgv23.Models.RealEstate.RealEstateIndexViewModel>

@{
    int rowNumber = 1;
}

<div>
    <a asp-action="create" asp-controller="RealEstate" type="submit">Create</a>
</div>

<div class="h1">
    Real Estates
</div>
<hr />
<form method="post">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Nr</th>
                <th scope="col">Location</th>
                <th scope="col">Size</th>
                <th scope="col">Room Number</th>
                <th scope="col">Building Type</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var realEstate in Model)
            {
                <tr>
                    <td>@rowNumber</td>
                    <td>@realEstate.Location</td>
                    <td>@realEstate.Size</td>
                    <td>@realEstate.RoomNumber</td>
                    <td>@realEstate.BuildingType</td>
                    <td>
                        <a asp-action="details" asp-controller="RealEstate" asp-route-id="@realEstate.Id">Details</a>
                        <a asp-action="update" asp-controller="RealEstate" asp-route-id="@realEstate.Id">Update</a>
                        <a asp-action="delete" asp-controller="RealEstate" asp-route-id="@realEstate.Id">Delete</a>
                    </td>
                </tr>

                rowNumber++;
            }
        </tbody>
    </table>
</form>